# Generated by Django 5.1.7 on 2025-03-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SerializerRelationships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="SerializerRelationships.author",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="book_genre",
            field=models.ManyToManyField(
                related_name="genre", to="SerializerRelationships.book"
            ),
        ),
    ]
