# Generated by Django 5.1.7 on 2025-03-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SerializerRelationships", "0002_alter_book_author_alter_genre_book_genre"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Author2",
        ),
        migrations.RenameModel(
            old_name="Book",
            new_name="Book2",
        ),
    ]
