# Generated by Django 5.1.7 on 2025-03-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SerializerRelationships", "0003_rename_author_author2_rename_book_book2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book2",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="SerializerRelationships.author2",
            ),
        ),
    ]
