# Generated by Django 5.1.7 on 2025-03-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SerializerRelationships", "0004_alter_book2_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="book_genre",
            new_name="book",
        ),
    ]
