# Generated by Django 5.1.7 on 2025-03-20 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClassBasedViewsBook", "0002_alter_book_published_date_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="book",
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="ClassBasedViewsBook.author",
            ),
        ),
    ]
