# Generated by Django 5.1.7 on 2025-03-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClassBasedViewsBook", "0003_remove_author_book_alter_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="books",
        ),
    ]
