# Generated by Django 5.1.7 on 2025-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="Published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
